// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArNXMA6w_CT_mXpmHekvWdUnAm2Xp7HUY',
    appId: '1:911628935073:web:5f429fa084de1c893d35e0',
    messagingSenderId: '911628935073',
    projectId: 'project1-khyle-flutter',
    authDomain: 'project1-khyle-flutter.firebaseapp.com',
    storageBucket: 'project1-khyle-flutter.appspot.com',
    measurementId: 'G-QQYWP3XKBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Bl0wVP7_mdBu_VxueAkYYEzcJOIiFQo',
    appId: '1:911628935073:android:fc7e7bf9b82b70773d35e0',
    messagingSenderId: '911628935073',
    projectId: 'project1-khyle-flutter',
    storageBucket: 'project1-khyle-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWIq-yyZfdosl6udgKNHpOnub6hsYPAE',
    appId: '1:911628935073:ios:fae3edbeb0da7d723d35e0',
    messagingSenderId: '911628935073',
    projectId: 'project1-khyle-flutter',
    storageBucket: 'project1-khyle-flutter.appspot.com',
    iosClientId: '911628935073-qf0jfr5cjepq2de8cl4gvg7s7otofabi.apps.googleusercontent.com',
    iosBundleId: 'com.azrael.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqWIq-yyZfdosl6udgKNHpOnub6hsYPAE',
    appId: '1:911628935073:ios:89650ec76b6148fa3d35e0',
    messagingSenderId: '911628935073',
    projectId: 'project1-khyle-flutter',
    storageBucket: 'project1-khyle-flutter.appspot.com',
    iosClientId: '911628935073-8tns02s6ho3hs86hfkjqptsltq6oaql5.apps.googleusercontent.com',
    iosBundleId: 'com.azrael.project1.RunnerTests',
  );
}
